# Generated by Django 3.2.3 on 2021-05-28 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=400)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('completed', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
